# Generated by Django 3.2.5 on 2023-10-26 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.TextField(blank=True)),
                ('title', models.TextField(blank=True)),
                ('year', models.TextField(blank=True)),
                ('filmurl', models.TextField(blank=True)),
                ('companyname', models.TextField(blank=True)),
                ('maincategory', models.TextField(blank=True)),
                ('maincategoryid', models.TextField(blank=True)),
                ('subcategory', models.TextField(blank=True)),
                ('roles', models.TextField(blank=True)),
                ('contactdetails', models.TextField(blank=True)),
                ('shortjobdescription', models.TextField(blank=True)),
                ('responsibilities', models.TextField(blank=True)),
                ('qualifications', models.TextField(blank=True)),
                ('comments', models.TextField(blank=True)),
                ('keywords', models.TextField(blank=True)),
                ('benchreparse', models.TextField(blank=True)),
                ('masteralias', models.TextField(blank=True)),
                ('masteraliascolumn', models.TextField(blank=True)),
                ('masteraliasinput', models.TextField(blank=True)),
                ('checkstatus', models.PositiveSmallIntegerField(default=1)),
                ('dropdownlist', models.TextField(default='New')),
            ],
        ),
    ]
